config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'
  resources :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    @employee = Employee.new
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end
 
 

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :index, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :designation, :exp, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class="ui-grid-a ">
      <%= form_for(@employee) do |f| %>
            <% if @employee.errors.any? %>
            <div id="error_explanation">
                  <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

                  <ul>
                      <% @employee.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                      <% end %>
                  </ul>
            </div>
            <% end %>
          



          
                  <div class="field">
                    
                    <%= f.text_field :name,:placeholder=>"Name" %>
                  </div>
                  <div class="field">
                    
                    <%= f.text_field :designation,:placeholder=>"designation" %>
                  </div>
         
                      
                  <div class="field">
                    
                    <%= f.number_field :exp,:placeholder=>"experience" %>
                  </div>
                  <div class="field">
                    
                    <%= f.text_field :location,:placeholder=>"location" %>
                 </div>
      
          <div class="field">
          <%= f.submit %>
         <%= link_to 'Back', '#pageone' , 'data-transition'=>"slide" ,'data-direction'=>"reverse"%>
          <% end %>
          </div>



</div>

app/views/employees/edit.html.erb
<div class="ui-grid-a ">
      <%= form_for(@employee) do |f| %>
            <% if @employee.errors.any? %>
            <div id="error_explanation">
                  <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

                  <ul>
                      <% @employee.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                      <% end %>
                  </ul>
            </div>
            <% end %>
          



          
                  <div class="field">
                    
                    <%= f.text_field :name,:placeholder=>"Name" %>
                  </div>
                  <div class="field">
                    
                    <%= f.text_field :designation,:placeholder=>"designation" %>
                  </div>
         
                      
                  <div class="field">
                    
                    <%= f.number_field :exp,:placeholder=>"experience" %>
                  </div>
                  <div class="field">
                    
                    <%= f.text_field :location,:placeholder=>"location" %>
                 </div>
      
          <div class="field">
          <%= f.submit %>
         <%= link_to 'Back', '#pageone' , 'data-transition'=>"slide" ,'data-direction'=>"reverse"%>
          <% end %>
          </div>



</div>

app/views/employees/index.html.erb
<div data-role="page" id="pageone">  
      <div data-role="main" class="ui-content">
        <div data-role="header">
          <h1>Employee database</h1>
        </div>

        <h1>Listing Employees</h1>

        <table data-role="table" class="ui-responsive">
          <thead>
            <tr>
              <th>Name</th>
              <th>Designation</th>
              <th>Exp</th>
              <th>Location</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @employees.each do |employee| %>
              <tr>
                <td><%= employee.name %></td>
                <td><%= employee.designation %></td>
                <td><%= employee.exp %></td>
                <td><%= employee.location %></td>
                <td><%= link_to 'Show', employee %></td>
                <td><%= link_to 'Edit', edit_employee_path(employee),'data-transition'=>"slide" %></td>
                <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'New Employee', '#pagetwo' , 'data-transition'=>"slide"%>
        </div>
</div>

<div data-role="page" id="pagetwo">
  <div data-role="main" class="ui-content">
  <div data-role="header">
    <h1>Add a new Employee</h1>
  </div>
    <%= render :partial=>"form" %>
  </div>
</div>


<div data-role="page">
  <div data-role="main" class="ui-content">
  <div data-role="header">
    <h1>Edit Employee</h1>
  </div>
    <%= render :partial=>"form" %>
  </div>
</div>

app/views/employees/show.html.erb
<div data-role="page">  
      <div data-role="main" class="ui-content">
	<p id="notice"><%= notice %></p>
	<div data-role="header">
          <h1>Details of <%=@employee.name%> </h1>
        </div>
	<p>
	  <strong>Name:</strong>
	  <%= @employee.name %>
	</p>

	<p>
	  <strong>Designation:</strong>
	  <%= @employee.designation %>
	</p>

	<p>
	  <strong>Exp:</strong>
	  <%= @employee.exp %>
	</p>

	<p>
	  <strong>Location:</strong>
	  <%= @employee.location %>
	</p>

	<%= link_to 'Edit', edit_employee_path(@employee) %> |
	<%= link_to 'Back', employees_path %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleCms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>
	<div data-role="footer">
  		<h1>me</h1>
	</div>

</body>
</html>